service: backend-pizzetos-api

frameworkVersion: '^3.0.0'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    FIREBASE_SERVICE_ACCOUNT_PATH: ./firebase-service-account.json
    ORDERS_TABLE: PizzetosOrders
    AWS_REGION: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt OrdersTable.Arn

functions:
  api:
    handler: src/app.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
      - http:
          path: /
          method: any
          cors: true

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PizzetosOrders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
